# Generated by Django 3.0.1 on 2019-12-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewssection',
            name='name',
        ),
        migrations.AlterField(
            model_name='viewssection',
            name='id_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_report.Section', verbose_name='Section_name'),
        ),
    ]
