# Generated by Django 3.0.1 on 2019-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_report', '0003_auto_20191222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_cart',
            field=models.CharField(max_length=30, verbose_name='Id_cart'),
        ),
    ]
