# Generated by Django 3.0.1 on 2019-12-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_report', '0005_pay_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='id_goods',
            field=models.CharField(default=8, max_length=30, verbose_name='Id_name'),
            preserve_default=False,
        ),
    ]
